//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kiemketaisan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiSan
    {
        public int Id { get; set; }
        public string TenTS { get; set; }
        public string NoiSuDung { get; set; }
        public Nullable<int> NamDVSD { get; set; }
        public Nullable<int> SoKiemKeTT { get; set; }
        public Nullable<int> SoTheoKeToan { get; set; }
        public string NguyenNhan { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public string GhiChu { get; set; }
    }
}
